[package]
name = "chip-8"
version = "0.1.0"
authors = ["Julián Sánchez <julian@jugacu.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_engine = "2.0.1"